### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ryzokuken** [ryzokuken/harbor#12]
# Pre `1.0.0`

## Critical

- [ ] Title
- [ ] Presentable UI/UX
- [x] Dev Page
- [x] Autohide menubar in windows

## Quality of Life

- [ ] Color Scheme/Status correlation

# Post `1.0.0`

- [ ] Rethink menubar
- [ ] Analytics (Data Counter)
- [ ] Quick Links
- [ ] Data Usage Notifications
- [ ] User-defined parameters (for notifications and quick links)
- [ ] Saved Accounts
- [ ] Autocycle
- [ ] Auto Updation
